{
  "comments": [
    {
      "key": {
        "uuid": "8e78bf3c_561ef4ca",
        "filename": "presubmit_canned_checks.py",
        "patchSetId": 2
      },
      "lineNbr": 114,
      "author": {
        "id": 1001934
      },
      "writtenOn": "2020-08-24T22:10:09Z",
      "side": 1,
      "message": "If the caller is: input_api.canned_checks.CheckAuthorizedAuthor(input_api, output_api)), then the caller gets this warning. Does that mean the caller must pass in |bot_allowlist|, or should this warning only print when |bot_whitelist| is not empty?",
      "revId": "149a3b7581257a60a3541e91875893088d68fb7f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "c1ee44cd_2cde68eb",
        "filename": "presubmit_canned_checks.py",
        "patchSetId": 2
      },
      "lineNbr": 114,
      "author": {
        "id": 1393469
      },
      "writtenOn": "2020-08-24T23:30:37Z",
      "side": 1,
      "message": "The warning should have been triggered only if bot_whitelist is defined. Thanks for catching it, I\u0027ll fix it.",
      "parentUuid": "8e78bf3c_561ef4ca",
      "revId": "149a3b7581257a60a3541e91875893088d68fb7f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "ca5a7728_962b16e9",
        "filename": "presubmit_canned_checks.py",
        "patchSetId": 2
      },
      "lineNbr": 630,
      "author": {
        "id": 1001934
      },
      "writtenOn": "2020-08-25T19:06:23Z",
      "side": 1,
      "message": "Similar issue here, and probably also with GetUnitTestsRecursively() below.",
      "revId": "149a3b7581257a60a3541e91875893088d68fb7f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}